Preview images aspect ratio
nextcloud/talk-ios pull request #648
Opened 2021-10-18 13:55 UTC by alazarevic5

It keeps the aspect ratio of the previewed images.

2021-10-18 15:06 UTC, SystemKeeper commented
Hey @alazarevic5 
just had a quick run on my phone (haven't looked at the code yet), when the image is too wide, the following happens:
![image](https://user-images.githubusercontent.com/1580193/137757567-7e874b30-c3fb-43bb-8d97-e3ed99f266b0.png)

2021-10-20 19:02 UTC, Ivansss requested changes

2021-10-20 19:02 UTC, Ivansss commented on NextcloudTalk/FileMessageTableViewCell.h
> +@property (atomic) int imageh;
We don't really need this property

2021-10-20 19:02 UTC, Ivansss commented on NextcloudTalk/FileMessageTableViewCell.m
> +    _previewImageView = [[FilePreviewImageView alloc] initWithFrame:CGRectMake(0, 0, kFileMessageCellFilePreviewHeight, self.imageh)];
We can remove this change and leave the default frame as CGRectMake(0, 0, kFileMessageCellFilePreviewHeight, kFileMessageCellFilePreviewHeight)

2021-10-20 19:02 UTC, Ivansss commented on NextcloudTalk/FileMessageTableViewCell.m
> +
We could combine this 2 into just one:
@"V:|-right-[titleLabel(28)]-left-[fileStatusView(previewSize)]-(>=0)-[statusView(statusSize)]-left-|"

2021-10-20 19:02 UTC, Ivansss commented on NextcloudTalk/FileMessageTableViewCell.m
> +        [self.contentView addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:@"V:|-left-[fileStatusView(previewSize)]-(>=0)-|" options:0 metrics:metrics views:views]];
Same here :)
@"V:|-left-[fileStatusView(previewSize)]-(>=0)-[statusView(statusSize)]-left-|"

2021-10-20 19:02 UTC, Ivansss commented on NextcloudTalk/FileMessageTableViewCell.m
> +                                        //[weakPreviewImageView setImage:image];
We can remove this commented code :)

2021-10-20 19:02 UTC, Ivansss commented on NextcloudTalk/FileMessageTableViewCell.m
> +                                           // weakPreviewImageView.layer.borderWidth = 1.0f;
And uncomment this one since we want to have the border :D

2021-10-20 19:02 UTC, Ivansss commented on NextcloudTalk/NCAPIController.m
> +    return previewRequest;
I would just leave this function as it was and just create the new one createPreviewRequestForFile: withMaxHeight:

2021-10-20 19:02 UTC, Ivansss commented on NextcloudTalk/NCChatViewController.m
> +    [self.tableView endUpdates];
Here we could use something like:

```
message.file.image_height = loadedImage.size.height;
    
NSIndexPath *indexPath = [self indexPathForMessage:message];
[self.tableView reloadRowsAtIndexPaths:@[indexPath] withRowAnimation:UITableViewRowAnimationNone];
```

2021-10-20 19:02 UTC, Ivansss commented on NextcloudTalk/NCMessageFileParameter.h
> +@property (nonatomic, assign) int image_height;
We could rename this property to `previewImageHeight`

2021-10-20 19:02 UTC, Ivansss commented on NextcloudTalk/NCChatViewController.m
> +
We don't need this since the height will be calculate it in getCellHeightForMessage

2021-10-20 19:25 UTC, SystemKeeper commented
Width looks good now 👍 

When entering a conversation, it's not scrolled down anymore:
![Simulator Screen Recording - iPhone 11 Pro - 2021-10-20 at 19 27 59](https://user-images.githubusercontent.com/1580193/138158348-2350e7b0-4f9b-495b-8e71-7d3918ba178b.gif)

Files without a preview (just with the placeholder) don't render correctly anymore:
![image](https://user-images.githubusercontent.com/1580193/138158643-f8ce6d85-f325-4ee1-a730-13c6dade95f6.png)
vs.
![image](https://user-images.githubusercontent.com/1580193/138158672-2ca39876-c107-4b69-81de-bb18cd200dcd.png)

2021-10-20 19:40 UTC, SystemKeeper commented on NextcloudTalk/FileMessageTableViewCell.m
> +                                            CGFloat width = [UIScreen mainScreen].bounds.size.width;
`width` is unused

2021-10-20 19:40 UTC, SystemKeeper commented on NextcloudTalk/FileMessageTableViewCell.m
> +                                                self.hPreviewSize[3].constant = (image.size.width > 230) ? 230 : image.size.width + 30;
Not sure, but if an image width is 229, we set it to 259 instead of limiting it to 230? Why the +30 here?
Or should the +30 added in both cases?

2021-10-20 19:40 UTC, SystemKeeper commented on NextcloudTalk/NCChatViewController.m
> +
So this needs to be moved to `getCellHeightForMessage` then? Otherwise `image_height` is not needed at all?!
(I'd also replace the 120 for `kFileMessageCellFilePreviewHeight`)

2021-10-27 14:05 UTC, Ivansss requested changes

2021-10-27 14:05 UTC, Ivansss commented on NextcloudTalk/FileMessageTableViewCell.m
> -        [self.contentView addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:@"V:|-right-[dateLabel(28)]-left-[previewImageView(previewSize)]-right-[bodyTextView(>=0@999)]-left-|" options
Vertical contraint for dataLabel was removed here and it was not added anywhere else.
This causes the dateLabel to be misplaced.
We should find a way to add a vertical contraint to the dateLabel. Maybe aligning it to titleLabel?

2021-10-27 14:05 UTC, Ivansss commented on NextcloudTalk/FileMessageTableViewCell.m
> +                                             } failure:nil];
Set proper indentation.

2021-10-27 14:05 UTC, Ivansss commented on NextcloudTalk/FileMessageTableViewCell.m
> +                                        }
Use `__weak typeof(self) weakSelf = self `to avoid retain cycle.
Then we can get rid of `__weak FilePreviewImageView *weakPreviewImageView = self.previewImageView;` and just use `weakSelf`

2021-10-27 14:05 UTC, Ivansss commented on NextcloudTalk/FileMessageTableViewCell.m
>      __weak FilePreviewImageView *weakPreviewImageView = self.previewImageView;
Use `__weak typeof(self) weakSelf = self `to avoid retain cycle.
Then we can get rid of `__weak FilePreviewImageView *weakPreviewImageView = self.previewImageView;` and just use `weakSelf`

2021-10-27 14:05 UTC, Ivansss commented on NextcloudTalk/NCAPIController.m
> -
No need to remove that new line :D

2021-10-29 10:49 UTC, Ivansss approved these changes

2021-10-29 10:49 UTC, merged